### ISSUE TITLE
Checklist for f/t

### ISSUE THREAD

**Issue by nawidj** [tacman-fp7/force-cop-estimator#3]
### Software
- [x] NI software
- [x] Config files with support for the new f/t
- [x] GURLS

### The device
- [x] Power supply
- [x] The NI DAQ
- [x] The sensor
- [x] USB cable
- [x] DAQ to SCU cable
